# Generated by Django 5.2 on 2025-05-03 09:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0002_chemist_doctor'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyCallReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('date', models.DateField(verbose_name='Date')),
                ('work_type', models.CharField(choices=[('field_work', 'Field Work'), ('office_work', 'Office Work'), ('leave', 'Leave'), ('holiday', 'Holiday')], default='field_work', max_length=20, verbose_name='Work Type')),
                ('summary', models.TextField(verbose_name='Summary')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, verbose_name='Submitted At')),
                ('chemists_visited', models.ManyToManyField(blank=True, related_name='dcr_visits', to='masters.chemist', verbose_name='Chemists Visited')),
                ('doctors_visited', models.ManyToManyField(blank=True, related_name='dcr_visits', to='masters.doctor', verbose_name='Doctors Visited')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_call_reports', to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Daily Call Report',
                'verbose_name_plural': 'Daily Call Reports',
                'ordering': ['-date', '-submitted_at'],
                'unique_together': {('user', 'date')},
            },
        ),
    ]
